# Generated by Django 4.0.8 on 2024-11-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
