# Generated by Django 4.0.8 on 2024-11-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed for this quiz.', verbose_name='Maximum Attempts'),
        ),
    ]
