# Generated by Django 4.0.8 on 2024-11-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of attempts allowed for this quiz.', verbose_name='Maximum Attempts'),
        ),
    ]
